version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gosec
    - errname
    - errorlint
    - gocritic
    - goconst
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      severity: medium
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
